# Generated by Django 3.2.15 on 2023-03-15 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOrder',
            new_name='OrderDetails',
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'элемент заказа', 'verbose_name_plural': 'Элементы заказа'},
        ),
    ]
