# Generated by Django 3.2.15 on 2023-03-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0003_alter_orderdetails_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('RE', 'Recive'), ('PR', 'Preparing'), ('DE', 'Delivery'), ('DO', 'Done')], default='no_status', max_length=10),
            preserve_default=False,
        ),
    ]
