# Generated by Django 3.2.15 on 2023-03-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0004_orderdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('RE', 'Recive'), ('PR', 'Preparing'), ('DE', 'Delivery'), ('DO', 'Done')], max_length=10, verbose_name='Статус'),
        ),
    ]
