# Generated by Django 3.2.15 on 2023-03-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0006_auto_20230329_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UN', 'Необработано'), ('RE', 'Получено'), ('PR', 'Подготовка'), ('DE', 'Доставка'), ('DO', 'Выполнено')], default='UN', max_length=10, verbose_name='Статус'),
        ),
    ]
