# Generated by Django 3.2.15 on 2023-03-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработано'), ('RE', 'Получено'), ('PR', 'Подготовка'), ('DE', 'Доставка'), ('DO', 'Выполнено')], default='unprocessed', max_length=20, verbose_name='Статус'),
        ),
    ]
