# Generated by Django 3.2.15 on 2023-03-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default=' ', verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
