# Generated by Django 3.2.15 on 2023-03-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0012_auto_20230329_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Безнал')], default='CASH', max_length=20, verbose_name='Cпособ оплаты'),
        ),
    ]
