# Generated by Django 4.2.1 on 2023-06-30 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0017_auto_20230508_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_products', to='foodcartapp.product', verbose_name='Товар'),
        ),
    ]
