# Generated by Django 4.2.1 on 2023-07-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0019_test4deploymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test4deploymodel',
        ),
    ]
